"""
Agent Composer — creates brand-new TIMPS agents from a natural-language brief.
Generates the Python file, registration snippet, and MCP tool description.

Input:  description (str), agent_name (str), model (str), dag_position (str), tools (list)
Output: agent_name, agent_function_code, code_path, registration_path, summary
"""
from __future__ import annotations

import re
from typing import Any, Dict, List

from src._helpers import _ts, _llm, _save, _parse_json, _record


def agent_composer(args: Dict[str, Any]) -> Dict[str, Any]:
    description = args.get("description", "")
    if not description:
        return {"error": "description is required"}

    agent_name = args.get("agent_name", "")
    model      = args.get("model", "qwen2.5:7b")
    dag_pos    = args.get("dag_position", "standalone")
    tools: List[str] = args.get("tools", [])

    if not agent_name:
        slug = re.sub(r"[^a-z0-9]+", "_", description.lower().strip())[:40].strip("_")
        agent_name = slug or "custom_agent"

    system = (
        "You are an expert AI agent architect. Given a brief, produce a complete Python "
        "agent function following the TIMPS pattern:\n"
        "- fn(args: dict) -> dict\n"
        "- Uses LLMRouter().call(agent_name, prompt, system_prompt)\n"
        "- Saves artefacts to generated/<subdir>/<name>.ext via _save()\n"
        "- Returns a dict with summary, relevant keys, file paths\n"
        "- Never raises — always returns gracefully\n\n"
        "Return JSON: {agent_function_code:str, system_prompt:str, "
        "input_schema:{prop:{type,description}}, output_schema:{prop:{type,description}}, "
        "dag_node_name:str, mcp_tool_description:str, recommended_model:str, "
        "required_packages:[str]}. Output ONLY valid JSON."
    )
    prompt = (
        f"Agent name: {agent_name}\nDescription: {description}\n"
        f"Model: {model}\nDAG position: {dag_pos}\n"
        f"Tools: {', '.join(tools) or 'none'}\n\n"
        "Generate the complete agent implementation."
    )

    data = _parse_json(_llm(prompt, system, "agent_composer"), {
        "agent_function_code": f"def {agent_name}(args):\n    return {{'summary': 'stub'}}",
        "system_prompt": "",
        "input_schema": {},
        "output_schema": {},
        "dag_node_name": agent_name,
        "mcp_tool_description": description,
        "recommended_model": model,
        "required_packages": [],
    })

    ts = _ts()
    full_code = (
        f'"""\nAuto-generated by Agent Composer — {ts}\n'
        f"Description: {description}\nModel: {data.get('recommended_model', model)}\n"
        f'"""\nfrom __future__ import annotations\nfrom src.llm_router import LLMRouter\n\n\n'
        + data.get("agent_function_code", "")
    )
    code_path = _save("code", f"{agent_name}_{ts}.py", full_code)

    reg = (
        f"# ── graph.py ─────────────────────────────────────────\n"
        f"# from generated.code.{agent_name}_{ts} import {agent_name}\n"
        f"# workflow.add_node('{data.get('dag_node_name', agent_name)}', {agent_name})\n\n"
        f"# ── llm_router MODEL_MAP ─────────────────────────────\n"
        f"# '{data.get('dag_node_name', agent_name)}': '{data.get('recommended_model', model)}',\n\n"
        f"# ── MCP description ──────────────────────────────────\n"
        f"# {data.get('mcp_tool_description', description)}\n"
    )
    reg_path = _save("code", f"{agent_name}_registration_{ts}.md", reg)

    _record("agent_composer", description, f"Created {agent_name}")
    return {
        "agent_name":          agent_name,
        "dag_node_name":       data.get("dag_node_name", agent_name),
        "agent_function_code": data.get("agent_function_code", ""),
        "system_prompt":       data.get("system_prompt", ""),
        "input_schema":        data.get("input_schema", {}),
        "mcp_tool_description":data.get("mcp_tool_description", description),
        "recommended_model":   data.get("recommended_model", model),
        "required_packages":   data.get("required_packages", []),
        "code_path":           code_path,
        "registration_path":   reg_path,
        "summary": (
            f"Agent '{agent_name}' composed at {code_path}. "
            f"Packages needed: {', '.join(data.get('required_packages', [])) or 'none'}."
        ),
    }
