"""
Shared state schema for the TIMPS Swarm multi-agent system.
All agents read/write to this shared state via LangGraph.
"""
from typing import Annotated, List, Optional, Dict, Any
from typing_extensions import TypedDict
import operator


class Task(TypedDict):
    id: str
    description: str
    assigned_to: str        # agent name
    status: str             # pending | running | completed | failed
    dependencies: List[str]
    output: Optional[str]
    artifact_path: Optional[str]
    created_at: Optional[str]
    completed_at: Optional[str]
    retry_count: int


class SwarmState(TypedDict):
    # Input
    user_request: str
    language: Optional[str]

    # Planning outputs
    requirements: str
    architecture_plan: str

    # Task management
    tasks: Annotated[List[Task], operator.add]

    # Code artifacts
    code_artifacts: Annotated[List[str], operator.add]

    # Review outputs
    review_comments: Annotated[List[str], operator.add]
    test_results: str
    security_report: str

    # Performance
    performance_report: str

    # Final output
    documentation: str
    final_deliverable: str

    # Control
    iteration_count: int
    max_iterations: int
    errors: Annotated[List[str], operator.add]
    completed: bool


class ComputerHealthState(TypedDict):
    """
    State for the 12 computer-health agents.
    These agents are standalone — they do NOT use the SDLC pipeline.
    Invoke via: from src.computer_agents import dispatch
    """
    # Input
    user_request: str

    # Per-agent outputs (keyed by agent name)
    reports: Annotated[List[Dict[str, Any]], operator.add]   # [{agent, report, report_path, ...}]

    # Collected action scripts (dry-run shell scripts)
    action_scripts: Annotated[List[str], operator.add]

    # Overall health summary generated by the LLM
    health_summary: Optional[str]

    # Which agents have run
    agents_run: Annotated[List[str], operator.add]

    # Errors from individual agents
    errors: Annotated[List[str], operator.add]


class KernelTask(TypedDict):
    """A single planned sub-task within an AgentKernel run."""
    id: str
    goal: str
    agent: str                   # which TIMPS agent handles it
    depends_on: List[str]
    status: str                  # pending | running | done | failed | skipped
    result: Optional[str]
    error: Optional[str]
    started_at: Optional[str]
    finished_at: Optional[str]
    retries: int


class KernelState(TypedDict):
    """Shared state for an AgentKernel delegated run."""
    run_id: str
    goal: str
    context: Dict[str, Any]
    tasks: Annotated[List[KernelTask], operator.add]
    status: str                  # planning | running | done | failed
    created_at: str
    finished_at: Optional[str]
    final_report: Optional[str]
    artifacts: Annotated[List[str], operator.add]
    errors: Annotated[List[str], operator.add]

    # Control
    completed: bool
